/**
 * Game phases
 */
export enum GamePhase {
  // System
  LOBBY = "LOBBY",
  GAME_OVER = "GAME_OVER",

  // Night
  NIGHT_MAFIA = "NIGHT_MAFIA",
  NIGHT_DON_CHECK = "NIGHT_DON_CHECK",
  NIGHT_SHERIFF_CHECK = "NIGHT_SHERIFF_CHECK",
  NIGHT_DOCTOR_HEAL = "NIGHT_DOCTOR_HEAL",

  // Day
  DAY_ANNOUNCE = "DAY_ANNOUNCE",
  DAY_BALAGAN = "DAY_BALAGAN",
  DAY_SPEECHES = "DAY_SPEECHES",
  DAY_DEFENSE = "DAY_DEFENSE",
  DAY_VOTE = "DAY_VOTE",
  DAY_REVOTE = "DAY_REVOTE",
}

/**
 * Players
 */
export enum Role {
  CIVILIAN = "CIVILIAN",
  SHERIFF = "SHERIFF",
  DOCTOR = "DOCTOR",
  MAFIA = "MAFIA",
  DON = "DON"
}

export enum Team {
  RED = "RED",
  BLACK = "BLACK"
}
